language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py34
  - TOXENV=py35

before_install:
  - 'sudo apt-get install libosmesa6-dev'

install:
  - pip install -e '.[dev]'

script:
  - tox


